/**
 * Land/ocean mask for the intro globe.
 *
 * The aerosol field was always a sphere — a lattice at radius 2.45 — but its
 * surface was three rotated sine lobes standing in for continents, so it read
 * as a planet rather than as Earth. This is the real coastline.
 *
 * Baked, not fetched. Natural Earth 110m land (public domain) rasterised to a
 * half-degree grid, supersampled and thresholded at 35% cell coverage, then
 * bit-packed: 259200 cells become 32400 bytes. An image would have been
 * sharper and also an async asset with a loading state and a first frame
 * without continents; this way the globe is correct on frame one.
 *
 * Half a degree rather than two. At two degrees the mask was the limit on how
 * clean the globe could get: the dot grid could be made as fine as you liked
 * and coastlines still came out in two-degree stair-steps. It also cost
 * accuracy — coastal cells rounding up to land put the area-weighted land
 * fraction at 0.307 against Earth's 0.292. At half a degree it is 0.294.
 *
 * Row 0 is +90 latitude, column 0 is -180 longitude.
 */

const W = 720;
const H = 360;

/**
 * Area-weighted share of the sphere this mask calls land, measured when the
 * mask was baked. Exported so samplers can solve for a land quota instead of
 * guessing a rejection rate and checking the result by eye.
 */
export const LAND_FRACTION = 0.294;

const PACKED =
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAED4AAA' +
  'AAAAAH/////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAH//////gAAAAD///////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////gB/B8P//////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH////////wf////////////8B/+AAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHx///////+D////////////////+AAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/8X//////h//' +
  '///////////////AAAAAAAAAAAAAAAAAAAAHvgAAAAAAAAAAAAB/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAB//+/P///8P////////////////gAAAAAAAAAAB//+AAAAAAHwAAAAAAAAAAAAAH//gAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAB///f////wAf///////////////AAAAAAAAAD8/z/+AAAAAAAAAAAAAAAAAAAAAA//4AAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAD//n//+AAD///////////////8AAAAAAAAAH//+AAAAAAAAAAAAA' +
  'AAAAAAAAAAAP/zwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHgA/4eD/////+AP////////////////4AAAAAA' +
  'AAAB//+AAAAAAAAAAAAAAAAAAAAAAAAAEH/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAB8fgDwf//8H////' +
  '/////////////4AAAAAAAAAAf/w8AAAAAAAAAAAAAAAAAAAAAAAAAf/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAfwAAAB8AD///AA/////////////////4AAAAAAAAAAD/g/AAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAB/wAAAAAAAAD//4AAA////////////////8AAAAAAAAAAD+AAAAAAAAAAAAAAAAAAAAAAAAAAAB/gAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/gAOAAAD/4f///AAH////////////////gAAAAAAAAAAAcAAAAAAAAAAAAAA' +
  'AA+AAAAAAAAAAD/8/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wfAfAB/4D+AQAgAAB////////////////gAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAP/+AAAAAAAAAD////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//H+B/4A/gD/AAAAAAA' +
  'f////////////4AAAAAAAAAAAAAAAAAAAAAAAAAH/8AAAAAAAAB///////AAAAAAAB//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'B///8APx8////wAAAAAAH////////////4AAAAAAAAAAAAAAAAAAAAAAAAD/8AAAAAAAAH////////AAAAAAAD//z+AAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAA/gAAAA+H///wAAAAAAB////////////wAAAAAAAAAAAAAAAAAAAAAAAAH/AAAAAAAAB////////gAA' +
  'AAAAAA8AgfAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/+AAAAAAAAAAAAAAAAAAAA////////////4AAAAAAAAAAAAAAAAAAAAAAAAf4' +
  'AAAAAAAAD///////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAAAAOA/+AAEwAAAAAAAf///////////gAAAAAA' +
  'AAAAAAAAAAAAAAAAAA/wAAAAAAA//////////+EAAAAAAAB8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH//8AAvgf8/4fj//4AAAAA' +
  'AP//////////8AAAAAAAAAAAAAAAAAAAAAAAAB/AAAAAAAB////////////8A/+AAAD+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/' +
  '//eZ/B/8/A///twAAAAAAD//////////4AAAAAAAAAAAAAAAAAAAAAAAAH8AAAA/hgB////////////////AAAH8AAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAf/n//+/Af+cB///v+AAAAAAD/////////+AAAAAAAAAAAAAAAAAAAAAAAAAP4AAAB/xx8/////////////' +
  '///AAAP//+AAAAAAAAAAAAAAAAAAAAAAAAAAAAf/f////gH+eA/////wAAAAAP//////////4AAAAAAAAAAAAAAAAAAAAAAAAf4A' +
  'AAD/jv/////////////////AwAH///gAAAAAAAAA+AAAAAADgAAAAAAAAAB8D////gAR/A//////gAAAAAf/////////8AAAAAAA' +
  'AAAAAAAAAIAAAAAAAD+AAAP/v//////////////////x//////8AAAAAAAADgAAAAAD//wAAAAAAAAAAH////4AB/wf/////8AAA' +
  'AB/////////4+AAAAAAAAAAAAAAA//AAAAAAAB/gAAf/j////////////////////////////gAAAAADAAAAAA////+AAAAACcAA' +
  'AH////gB/4B//////wAAAD//////////gAAAAAAAAAAAAAA///gAAAAAAAAAAAP/z////////////////////////////wAAAAAA' +
  'AAAAAD///////gAB//c8B/////w+fwAH5B///4AAAD+/////////wAAAAAAAAAAAAAP///2AAAAAAAAA+AP/3///////////////' +
  '/////////////wCAD//AAAAAAP///////+D/////4f////B/n+QH+AH//8AAAAQ////////8AAAAAAAAAAAAAA/////wAAAAAAAA' +
  'f8D/n///////////////////////////////x//+wAAAH////////////////+f/MAABH+8P/AD//wAAAAB////////gAAAAAAAA' +
  'AAAAAH//////8AAAADgMf/h/5///////////////////////////////////+AAAH/////////////////AB/gAfP/8P+ACP/8AA' +
  'AAP///////wAAAAAAAAAAAAAAf///////gH4A/P/////5////////////////////////////////////wAAA///////////////' +
  '///5//D///8f+APD//4AAAf//////gAAAAAAAAAAAAAAB////////4D4P///////4///////////////////////////////////' +
  '/8AAAP///////////////////////////AOD//8AAA//////+AAAAAAAAAAAAAAAD////////8Dg////////j///////////////' +
  '/////////////////////9+AAB//////////////////////////8AAH///wAAf/////8AAAAAAAAAAAAAAAH////////8B/////' +
  '////H//////////////////////////////////////gD5/////////////////////////yAAAP/x/wAAf/////gAAAeEPgAAAA' +
  'AAAAf//////wf57/////////////////////////////////////////////v//w///////////////////////////oAAAf/w/g' +
  'AAP////wAAAA///gAAAAAAAA///4f//8AH//////////////////////////////////////////////gf4Af///////////////' +
  '///////////PAA///8PAAAH///8AAAAAH//4AAAAAAAB///gP//8AP//////////////////////////////////////////////' +
  'AH4AH//////////////////////////f4B////AAAAH///4AAAAAf//wAAAAAAAD///g///8fP//////////////////////////' +
  '///////////////////+AA4AAAP///////////////////////8f+AgH//wAAAD///4AAAAAH/+AAAAAAAAP///j////P///////' +
  '///////////////////////////////////////wAAAQAAP//////////////////////+A/vwAB//wAAAD///wAAAAAB/gAAAAA' +
  'AAA///+P///////////////////////////////////////////////////4AAAcAL///////////////////////+AMAAAA//4A' +
  'AAB///gAAAAAAAAAAAAAAAD///4f///////////////////////////////////////////////////8AAAAA///////////////' +
  '/////////wAAcAAAP8QAAAAf/+AAAAAAAAAAAAAAAA////A////////////////////////////////////////////////////+' +
  'AAAAB////////////////////////gAA4Y/8A/AAAAAP/+AAAAAAAAAAAAAAAB///+A/////////////////////////////////' +
  '//////////////z///+AAAAAD///////////////////////+AAAAI//AAAAAAAH/+AAAAAAAAAAAAAAAD///+Af////////////' +
  '//////////////////////////////////z///wAAAAAD///////////////////////8AAAAA//gAAAAAAD/+AAAAAAAAAAAAAA' +
  'AD///+Af////////////////////////////////////////////gfH//8AAAAAAB/////8/////////////////8AAAAA//+AAA' +
  'AAAAD8AAAAAAAAAAAAAAAD///+A/////////////////////////////////////////////AIf//wAAAAAAe////v8H////////' +
  '////////4AAAAAf/+AIAAAAAB8AAAAAAAAAAAAAAAD////gH4H/////////////////////////////////////////8AB//GAAA' +
  'AAAAEJ///PgAA///////////////4AAAAAf/+AcAAAAAAAAAAAAAAAAAAAAAAD////gAAH//////////////////////////////' +
  '///////////4AH5IAAAAAAAAAA//+MAAAH//////////////4AAAAA///A+AAAAAAAAAAAAAAAAAAAAAAD////gB////////////' +
  '////////////////////////////A8P8AP4AAAAAAAAAAAz/+AAAAB///////////////AAAAB///x/AAAAAAAAAAAAAAAAAAAAA' +
  'AB/j/8AB///////////////////////////////////////wAAAAA/wAAAAAAAAAAAAH8AAAAAP//////////////AAAAA/////g' +
  'AAAAAAAAAAAAAAAAAAeAAAeD/8AA///////////////////////////////////////AAAAAB/gAAAAAAAAAAAAPzwAAAAAP////' +
  '/////////gAAAAP////wAAAAAAAAAAAAAAAAAA/wAAAB/4AA//////////////////////////////////////8AAAAAf/wAAAAA' +
  'AAAAAAAfPgAAAAAH/////////////yAAAAP////4AAAAAAAAAAAAAAAAAA/wAAA5/4Ae////////////////////////////////' +
  '//////4AAAAAf/4AAAAAAAAAAAB8EAAAAAAD//////////////4AAAH////4AAAAAAAAAAAAAAAAAA/gAAD4/4A/////////////' +
  '//////////////////////////gAAAAA//4AAAAAAAAAAAHwAAAAAAAB//////////////+AAAP////8AAAAAAAAAAAAAAAAAA/g' +
  'AAD8fwA//////////////////////////////////////+AAAAAB//wAAAAAAAAAAB/AAAAAAAAA///////////////wAAf/////' +
  'AAAAAAAAAAAAAAAAAAfwAADz+AA//////////////////////////////////////8AAAAAB//AAAAAAAAAAAHgAAAAAAAAAf///' +
  '////////////wA//////gAAAAAAAAAAAAAAAACP4AADzgAA//////////////////////////////////////wAAAAAB//AAAAAA' +
  'AAAAA8AAAAAAAAAAP///////////////8H//////+AAAAAAAAAAAAAAAAPv8AABwADn/////////////////////////////////' +
  '/////gAAAAAB//AAAAAAAAAAAAAAAAAAAAAAH///////////////4H///////AAAAAAAAAAAAAAAA/B/AAB94///////////////' +
  '/////////////////////////8cEAAAB/4AAAAAAAAAAAAAAAAAAAAAHj///////////////8D///////gAAAAAAAAAAAAAAD/A/' +
  'AAP///////////////////////////////////////////+EAAAB/4AAAAAAAAAAAAAAAAAAAAADB///////////////8D//////' +
  '/4AAAAAAAAAAAAAAB/P/gD/////////////////////////////////////////////8AAAA/wAAAAAAAAAAAAAAAAAAAAABA///' +
  '////////////+D///////4AAAAAAAAAAAAAAB/H/8H/////////////////////////////////////////////+AAAA+AAAAAAA' +
  'AAAAAAAAAAAAAAAAgP//////////////+D///////4AAAAAAAAAAAAAAB+H/4P//////////////////////////////////////' +
  '///////+AAAA+AAAAAAAAAAAAAAAAAAAAAAAAP///////////////j///////wAAAAAAAAAAAAAADgP/4f//////////////////' +
  '///////////////////////////eAAAAcAAAAAAAAAAAAAAAAAAAAAAAAP//////////////////////+4AAAAAAAAAAAAAAAAH/' +
  '5//////////////////////////////////////////////OAAAAYAAAAAAAAAAAAAAAAAAAAAAAAX//////////////////////' +
  'xwAAAAAAAAAAAAAAAAP/3/////////////////////////////////////////////+PAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//' +
  '////////////////////DwAAAAAAAAAAAAAAAAaAH/////////////////////////////////////////////+PAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAH///////////////////8HgD4AAAAAAAAAAAAAAAAAI////////////////////////////////////////' +
  '//////+PgAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9//////////////////wQwH/gAAAAAAAAAAAAAAAAP////////////////////' +
  '//////////////////////////+PgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAe//////////////////H4AP/wAAAAAAAAAAAAAAAH/' +
  '//////////////////////////////////////////////+MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOf////////////////+fwA' +
  'P/wAAAAAAAAAAAAAAAH///////////////////////////////////////////////8MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHf' +
  '////////////////9/wAf/4AAAAAAAAAAAAAAAD///////////////////////////////////////////////4MAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAH/////////////////7/4AAE4AAAAAAAAAAAAAAAAf////////////////////////////////////////' +
  '//////wOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///////////////////+CABwAAAAAAAAAAAAAAAAP////////////z///+D//' +
  '//////////////////////////gOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////////////////////3AAAAAAAAAAAAAAAAAAAH' +
  '//////////h8D///wB////////////////////////////gIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////' +
  'AAAAAAAAAAAAAAAAAAAH//////////A8H///gD////////////////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/' +
  '///////////////////8AAAAAAAAAAAAAAAAAAAH////n/////B////+Af///////////////////////////8AYAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAD//////////////////8fAAAAAAAAAAAAAAAAAAAAH////g////8A8H//8Af//////////////////////' +
  '/////4AcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////////////////w8AAAAAAAAAAAAAAAAAAAAH//+/g////8AAB//8B///' +
  '/////////////////////////wAfIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////8AwAAAAAAAAAAAAAAAAAAIAP' +
  '//8P4P///4AAAf/+A////////////////////////////gAf4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/////////////////4AAA' +
  'AAAAAAAAAAAAAAAAB////xwH8H///wAAAP/+Af///////////////////////////AD/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/' +
  '////////////////4AAAAAAAAAAAAAAAAAAAA////AAn8B///wAAAD/+AH/////////////////////////+MAD/AAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAH/////////////////4AAAAAAAAAAAAAAAAAAAA////ABh/Af//wAAAB//AH//////////////////////' +
  '///8AAHmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/////////////////8AAAAAAAAAAAAAAAAAAAA////ABg/wH//wD/gB//gE//' +
  '///////////////////////wAADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/////////////////gAAAAAAAAAAAAAAAAAAAA///' +
  '8AAgf8H//+P/4H//wAf////////////////////////wAADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH////////////////+AAAA' +
  'AAAAAAAAAAAAAAAAA///wADgD/P/Dj//////4C/////////////////////////gAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/' +
  '///////////////wAAAAAAAAAAAAAAAAAAAAA///gABwA9n/j///////4D//////////////////////j//AAADwAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAD////////////////wAAAAAAAAAAAAAAAAAAAAA///AABwAYD8B///////4B/////////////////////+' +
  'H38AAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////////////////gAAAAAAAAAAAAAAAAAAAAB///AABwAOB+B///////4D//' +
  '///////////////////8GD8AAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB////////////////AAAAAAAAAAAAAAAAAAAAAB///' +
  'AAAAAIB+B///////wA/////////////////////wAD+AAAHgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////AAAAA' +
  'AAAAAAAAAAAAAAAAA//+AAAAAYA/D///////wA/////////////////////wAH/AAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/' +
  '//////////////+AAAAAAAAAAAAAAAAAAAAAA//+AAAAfgA/A///////wA/////////////////////8YD/AAAPAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAf//////////////8AAAAAAAAAAAAAAAAAAAAAA//4AAA4PgAcA///////+A//////////////////////' +
  '+AfgAE/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//////////////8AAAAAAAAAAAAAAAAAAAAAAB/wA//8BgAMAf//////////' +
  '////////////////////8A/gAH/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//////////////8AAAAAAAAAAAAAAAAAAAAAAAwA' +
  'f//4AAAAABjx////////////////////////////wA/gAP/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH//////////////+AAAAA' +
  'AAAAAAAAAAAAAAAAAAwH///8AAAAAAAA////////////////////////////AAfgBf/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD' +
  '//////////////8AAAAAAAAAAAAAAAAAAAAAAB/////8AAAB8ABw///////////////////////////+AAfgf/+AAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAD//////////////4AAAAAAAAAAAAAAAAAAAAAAB/////4AAAAAABg///////////////////////////+' +
  'AAcB//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////////////gAAAAAAAAAAAAAAAAAAAAAAD/////4AAAAAAAB////////' +
  '////////////////////gAAD28AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH////////////+AAAAAAAAAAAAAAAAAAAAAAAP//' +
  '///8AAAAAAAD////////////////////////////gAAGf4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB////////////8AAAAAA' +
  'AAAAAAAAAAAAAAAAAf/////+AAAAAAAD////////////////////////////wAAf6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'B////////////4AAAAAAAAAAAAAAAAAAAAAAA///////8AB4AAAD////////////////////////////wAAfAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAA////////////gAAAAAAAAAAAAAAAAAAAAAAB////////gD/AAAH////////////////////////////' +
  '4AAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////AAAAAAAAAAAAAAAAAAAAAAAB////////gH/wAAH////////' +
  '////////////////////8AAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAef/////////+AAAAAAAAAAAAAAAAAAAAAAAD///' +
  '/////8D//h+P////////////////////////////8AAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeP/////////+AAAAAAA' +
  'AAAAAAAAAAAAAAAAD/////////n/////////////////////////////////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AOP///////yf/AAAAAAAAAAAAAAAAAAAAAAAB///////////////////////////////////////////4AAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAPH///////gGfAAAAAAAAAAAAAAAAAAAAAAAD///////////////////j///////////////////////' +
  '8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADn/////wDwAPAAAAAAAAAAAAAAAAAAAAAAAH///////////////////B///' +
  '////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABz/////gAAAPgAAAAAAAAAAAAAAAAAAAAAAP///' +
  '////////////////g///////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABx////+AAAAPgAAAAAA' +
  'AAAAAAAAAAAAAAAA////////////////////g///////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AD4////8AAAAPgAAAAAAAAAAAAAAAAAAAAAD///////////////z////wP//////////////////////wAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAB8f///4AAAAHwAAAAAAAAAAAAAAAAAAAAAH///////////////x////4H//////////////////////' +
  'gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+P///4AAAAHzwAAAAAAAAAAAAAAAAAAAAP///////////////w////8B4/' +
  '////////////////////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOH///8AAAADwQAAAAAAAAAAAAAAAAAAAAf////' +
  '///////////w////+AC/////////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHH///8AAAABwAAAAAA' +
  'AAAAAAAAAAAAAAA////////////////4f///+gGf///////////////////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AADB///4AAAABhAAAAAAAAAAAAAAAAAAAAA////////////////8P////gOAf8f////////////////+AAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAHg///4AAAAABgAAAAAAAAAAAAAAAAAAAA////////////////8P////geAAAP////////////////8' +
  'MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwf//4AAAAAAgAAAAAAAAAAAAAAAAAAAB////////////////+H////0/A' +
  'AAP////////////////4cAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYP//4AAAAAAgAAAAAAAAAAAAAAAAAAAD/////' +
  '///////////+B//////4AAD////////////////g4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYH//4AAAAEAAAAAAA' +
  'AAAAAAAAAAAAAAH////////////////+B//////8AAA////////////////A4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAD//4AAAA/4AAAAAAAAAAAAAAAAAAAAH/////////////////A//////+AAAf//////////////8A4AAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAD//4AAABj/AAAAAAAAAAAAAAAAAAAAH/////////////////w///////AAA///////n//////+AA' +
  'QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//4AAACAfwAAAAAAAAAAAAAAAAAAAP/////////////////w//////+' +
  'AAAf/////8D//////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAAAAAAAAAAAAAAB//4AA/gAB8AAAAAAAAAAAAAAAAAAAP/////' +
  '////////////4//////8AAAP/////AD////+HAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAB//8AB/AAA/AAAAA' +
  'AAAAAAAAAAAAAAP/////////////////wf/////8AAACf////AB////8GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAA' +
  'AAAAD//8AB/AAAfwAAAAAAAAAAAAAAAAAAH/////////////////wP/////wAAAAf///+AB////4CAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAwAAAAAAAAAAAAAAAB//+AB+AAAAH4AAAAAAAAAAAAAAAAAH/////////////////wH/////gAAAAf///8AAf///wPAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAA///AD+AAAAD/AAAAAAAAAAAAAAAAAH/////////////////4D/////w' +
  'AAAAf///wAAf///wfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//gf+AAAAB/gAAAAAAAAAAAAAAAAH/////' +
  '////////////4D/////AAAAAP///gAAP///weAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH//7/8AAB4f8ngA' +
  'AAAAAAAAAAAAAAD/////////////////8B////+AAAAAP///AAAP///4IAAAeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAA////8AAAQAQAAAAAAAAAAAAAAAAAH/////////////////+B////4AAAAAP//+AAAH///8AAAAeAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAP///8AAAAAAAAAAAAAAAAAAAAAAAH//////////////////A////4AAAAAP//4AAAH///8AAAA' +
  'eAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAAAAAAAAAAAAAAAAAAAAAAH//////////////////Af///AA' +
  'AAAAH//4AAAH///+AAAA+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//4AAAAAAAAAAAAAAAAAAAAAAAH/////' +
  '/////////////gf//4AAAAAAH//wAAAPn///AAAA+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADD///AAAAAAAA' +
  'AAAAAAAAAAAAAAP//////////////////gf//4AAAAAAH/+AAAAGH///gAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAA///gAAAAAAAAAAAAAAAAAAAAAP//////////////////wf//gAAAAAAD/8AAAAAH///wAAA4AAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//wAAAAAAAAAAAAAAAAAAAAAf//////////////////8f/8AAAAAAAD/8AAAAAH///wAAA' +
  '8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//wAAAAAAAAAAAAAAAAAAAAAP//////////////////+P/wAAA' +
  'AAAAB/+AAAAAD///4AAAfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//gAAAAAAAAAAAAAAAAAAAAAP/////' +
  '//////////////P+AAAAAAAAB/+AAAAAD///4AAAfwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/gAAAAAAA' +
  'AAAAAAAAAAAAAAP///////////////////vwAAAAAAAAB/+AAAAAB///4AAAYwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAB/gAAAAAAAAAAAAAAAAAAAAAP////////////////////AAAAAAAAAA/+AAAAAB3//4AAAIYAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/gAAAwAAAAAAAAAAAAAAAAAH///////////////////4AAAAAAAAAA/8AAAAABwf/4AAA' +
  'AGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfgAAD2AAAAAAAAAAAAAAAAAH///////////////////wADAAA' +
  'AAAAAf8AAAAABwf/4AAACGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPgAAfvgAAAAAAAAAAAAAAAAB/////' +
  '//////////////4A/AAAAAAAAf8AAAAABgP/gAAADPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPgAB//wB8' +
  'AAAAAAAAAAAAAAA///////////////////8f/AAAAAAAAP8AAAAABgP/AAADD2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAPwAB///vsAAAAAAAAAAAAAAAf/////////////////////AAAAAAAAP4AAAAABgB8AAAGB0AAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH4AB/P//8AAAAAAAAAAAAAAAP/////////////////////AAAAAAAAPyAAAAABAA4AAAE' +
  'BgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8PH////+AAAAAAAAAAAAAAAH////////////////////+AAA' +
  'AAAAAHzAAAAADwBwAAAYBhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/7/////+AAAAAAAAAAAAAAAH////' +
  '////////////////+AAAAAAAAHngAAAADwAgAAAQAHgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPx//////' +
  'gAAAAAAAAAAAAAAD////////////////////+AAAAAAAADHgAAAAD4AAAAAAB/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAABx//////4AAAAAAAAAAAAAAD////////////////////8AAAAAAAAAHwAAAAA4AAAAAAD/gAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAg//////4AAAAAAAAAAAAAAB////////////////////8AAAAAAAAADwAAAAAcAAAAAA' +
  'DPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////8AAAAAAAAAAAAAAAf///////////////////4AAA' +
  'AAAAAADgAAAAAeAAAABgAOgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////+AAAAAAAAAAAAAAAP///' +
  '////////////////wAAAAAAAAADgAAAAAPgAAADwAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////' +
  '//gAAAAAAAAAAAAAH///wD//////////////wAAAAAAAAAAAAAAAAPwAAAH4ACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAf///////4AAAAAAAAAAAAAB//+AD//////////////gAAAAAAAAAAAAAAD4P4AAAP+AAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf///////8AAAAAAAAAAAAAA+AIAB//////////////AAAAAAAAAAAAAAAB8H4AAAf4' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf///////+AAAAAAAAAAAAAAAAAAAx/////////////AAAA' +
  'AAAAAAAAAAAA+H4AAA/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf////////AAAAAAAAAAAAAAAAA' +
  'AAA////////////+AAAAAAAAAAAAAAAAfD4AAB/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////' +
  '///AAAAAAAAAAAAAAAAAAAAf///////////8AAAAAAAAAAAAAAAAPz4AAD/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAA/////////gAAAAAAAAAAAAAAAAAAAf///////////4AAAAAAAAAAAAAAAAHx8AAf/wAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/////////gAAAAAAAAAAAAAAAAAAAf///////////wAAAAAAAAAAAAAAAAD48AA//w' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////wAAAAAAAAAAAAAAAAAAAf///////////AAAAA' +
  'AAAAAAAAAAAAB/eAP//wAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/////////wAAAAAAAAAAAAAAAA' +
  'AAA///////////+AAAAAAAAAAAAAAAAAB/mAP//4AEHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//////' +
  '///wAAAAAAAAAAAAAAAAAAA///////////8AAAAAAAAAAAAAAAAAA/wAP//w/8HAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAf/////////gAAAAAAAAAAAAAAAAAAA///////////wAAAAAAAAAAAAAAAAAA/8AP//hgQGAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////////+AAAAAAAAAAAAAAAAAAA///////////wAAAAAAAAAAAAAAAAAAf8AP//h' +
  'gAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////////+wAAAAAAAAAAAAAAAAAB///////////gAAAAA' +
  'AAAAAAAAAAAAAP4AP//hjgCB8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///////////+AAAAAAAAAAAAAAA' +
  'AAB///////////AAAAAAAAAAAAAAAAAAAH+AH//D+AAH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///////' +
  '/////gAAAAAAAAAAAAAAAAA//////////+AAAAAAAAAAAAAAAAAAAH+AD/+D8AAA+DgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAA////////////gAAAAAAAAAAAAAAAAAf/////////8AAAAAAAAAAAAAAAAAAAD/AD/+D8AAA+P8AAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////////////AAAAAAAAAAAAAAAAAP/////////4AAAAAAAAAAAAAAAAAAAB/wD/+H' +
  '8AAg+P/gAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////////////AAAAAAAAAAAAAAAAH/////////wAAAAAA' +
  'AAAAAAAAAAAAAB/wAN+DuA74f//8AAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//////////////gAAAAAAAAAAAA' +
  'AAAD/////////wAAAAAAAAAAAAAAAAAAAA/wAAeBuAQEf///gADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB///////' +
  '///////wAAAAAAAAAAAAAAAD/////////gAAAAAAAAAAAAAAAAAAAAfwAAABnAAAB///wAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAB//////////////8AAAAAAAAAAAAAAAB/////////gAAAAAAAAAAAAAAAAAAAAPwAAABngAAAP//4AGAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB///////////////gAAAAAAAAAAAAAAA/////////AAAAAAAAAAAAAAAAAAAAADwAAAB' +
  'jAAAAB//8AsEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///////////////wAAAAAAAAAAAAAAA/////////AAAAAAA' +
  'AAAAAAAAAAAAAABwAAABAAAADA///H4GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///////////////wAAAAAAAAAAA' +
  'AAAA/////////AAAAAAAAAAAAAAAAAAAAAAfAAAAAAAADA///xgCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//////' +
  '////////wAAAAAAAAAAAAAAAf////////gAAAAAAAAAAAAAAAAAAAAAfxwAAAAAACAf//AABQAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAP//////////////4AAAAAAAAAAAAAAAf////////gAAAAAAAAAAAAAAAAAAAAAP/8AAAAAAAAf//gAAIAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH//////////////4AAAAAAAAAAAAAAAP////////gAAAAAAAAAAAAAAAAAAAAAAv/gA' +
  'AAAAAA//vwAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH//////////////wAAAAAAAAAAAAAAAP////////gAAAAAA' +
  'AAAAAAAAAAAAAAAAAf4cRAQAABz+D4AAA0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////////////wAAAAAAAAAAA' +
  'AAAAP////////gAAAAAAAAAAAAAAAAAAAAAAAAQ88DwAAAB+B4AAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////' +
  '////////wAAAAAAAAAAAAAAAP////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAAAEA+AAACAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAB//////////////gAAAAAAAAAAAAAAAP////////wAAAAAAAAAAAAAAAAAAAAAAAAADgcAAAAAAAfAAAcAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//////////////AAAAAAAAAAAAAAAAP////////4AAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'wQAAAAAAAHwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////////////+AAAAAAAAAAAAAAAAH////////4AAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////////////8AAAAAAAAAAAA' +
  'AAAAH////////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////' +
  '///////4AAAAAAAAAAAAAAAAH////////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAP////////////4AAAAAAAAAAAAAAAAH////////4AAIAAAAAAAAAAAAAAAAAAAAAAAAAAD/8AeAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////////////wAAAAAAAAAAAAAAAAP////////4AAMAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAH/8AeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH////////////gAAAAAAAAAAAAAAAAf////////4AAcAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAP/4AeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH////////////AAAAAAAAAAAAA' +
  'AAAAf////////4AA8AAAAAAAAAAAAAAAAAAAAAAAAAAf/wAeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/////' +
  '///////AAAAAAAAAAAAAAAAA/////////4AA+AAAAAAAAAAAAAAAAAAAAAAAAA8f/wAfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAD////////////AAAAAAAAAAAAAAAAA/////////8AB+AAAAAAAAAAAAAAAAAAAAAAAAD+//gAf4AAAAAAEAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB////////////AAAAAAAAAAAAAAAAA/////////4AD+AAAAAAAAAAAAAAAAAAAAAAA' +
  'AH///wAf4AAAAAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf///////////AAAAAAAAAAAAAAAAB/////////4Af+AAA' +
  'AAAAAAAAAAAAAAAAAAAAAH///8Af4AAAAAACAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////////AAAAAAAAAAAAA' +
  'AAAB/////////wB/8AAAAAAAAAAAAAAAAAAAAAAAAf///+A/4AAAAAADAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////' +
  '///////AAAAAAAAAAAAAAAAB/////////gD/8AAAAAAAAAAAAAAAAAAAAAAAB/////g/8AAAAAAAAAAGAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAA///////////AAAAAAAAAAAAAAAAB////////+AD/4AAAAAAAAAAAAAAAAAAAAAAAD/////4/8AAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//////////AAAAAAAAAAAAAAAAB////////4AD/4AAAAAAAAAAAAAAAAAAAAAAA' +
  'D///////8AAAAAAAAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/////////+AAAAAAAAAAAAAAAAA////////gAD/4AAA' +
  'AAAAAAAAAAAAAAAAAAAAD///////8AAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/////////+AAAAAAAAAAAAA' +
  'AAAA////////AAD/4AAAAAAAAAAAAAAAAAAAAAAAH///////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH///' +
  '//////+AAAAAAAAAAAAAAAAAf//////+AAD/wAAAAAAAAAAAAAAAAAAAAAAAP////////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAD/////////8AAAAAAAAAAAAAAAAAf//////8AAB/wAAAAAAAAAAAAAAAAAAAAAAAf////////wAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////8AAAAAAAAAAAAAAAAAP//////8AAD/wAAAAAAAAAAAAAAAAAAAAAAH' +
  '/////////8AAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////4AAAAAAAAAAAAAAAAAP//////8AAD/gAAA' +
  'AAAAAAAAAAAAAAAAAAB//////////8AAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////4AAAAAAAAAAAAA' +
  'AAAAH//////+AAH/gAAAAAAAAAAAAAAAAAAAAAH//////////+AAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///' +
  '//////wAAAAAAAAAAAAAAAAAD//////+AAP/gAAAAAAAAAAAAAAAAAAAAAf//////////+AAAAAYAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAH/////////gAAAAAAAAAAAAAAAAAD//////+AAP/AAAAAAAAAAAAAAAAAAAAAB////////////gAAAAEAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/////////gAAAAAAAAAAAAAAAAAB//////+AAH/AAAAAAAAAAAAAAAAAAAAAB//' +
  '//////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH////////wAAAAAAAAAAAAAAAAAAB//////+AAH/AAAA' +
  'AAAAAAAAAAAAAAAAAB////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH////////AAAAAAAAAAAAAAA' +
  'AAAAB//////+AAH+AAAAAAAAAAAAAAAAAAAAAB////////////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH///' +
  '////4AAAAAAAAAAAAAAAAAAAB//////+AAH+AAAAAAAAAAAAAAAAAAAAAB////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAH///////wAAAAAAAAAAAAAAAAAAAB//////4AAD+AAAAAAAAAAAAAAAAAAAAAB////////////+AAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////AAAAAAAAAAAAAAAAAAAAB//////gAAB4AAAAAAAAAAAAAAAAAAAAAA//' +
  '///////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////AAAAAAAAAAAAAAAAAAAAB//////AAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAB/////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//////+AAAAAAAAAAAAAAAA' +
  'AAAAA//////AAAAAAAAAAAAAAAAAAAAAAAAAAB/////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///' +
  '///+AAAAAAAAAAAAAAAAAAAAA//////AAAAAAAAAAAAAAAAAAAAAAAAAAB/////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAP//////+AAAAAAAAAAAAAAAAAAAAA/////+AAAAAAAAAAAAAAAAAAAAAAAAAAA/////////////gAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//////+AAAAAAAAAAAAAAAAAAAAAf////+AAAAAAAAAAAAAAAAAAAAAAAAAAA//' +
  '///////////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//////+AAAAAAAAAAAAAAAAAAAAAP////+AAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAA/////////////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//////8AAAAAAAAAAAAAAAA' +
  'AAAAAH////+AAAAAAAAAAAAAAAAAAAAAAAAAAAf////////////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf///' +
  '///4AAAAAAAAAAAAAAAAAAAAAH////4AAAAAAAAAAAAAAAAAAAAAAAAAAAP////////////gAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAf//////wAAAAAAAAAAAAAAAAAAAAAD////wAAAAAAAAAAAAAAAAAAAAAAAAAAAP////////////gAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//////wAAAAAAAAAAAAAAAAAAAAAD////wAAAAAAAAAAAAAAAAAAAAAAAAAAAP/' +
  '///////////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///////gAAAAAAAAAAAAAAAAAAAAAB////gAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAP////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///////AAAAAAAAAAAAAAAAA' +
  'AAAAAA////AAAAAAAAAAAAAAAAAAAAAAAAAAAAH////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf///' +
  '//+AAAAAAAAAAAAAAAAAAAAAAA///+AAAAAAAAAAAAAAAAAAAAAAAAAAAAH////B///////AAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAf/////8AAAAAAAAAAAAAAAAAAAAAAA///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAH///4AP/////+AAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////4AAAAAAAAAAAAAAAAAAAAAAA///4AAAAAAAAAAAAAAAAAAAAAAAAAAAAH/' +
  '/+AAD/////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//////4AAAAAAAAAAAAAAAAAAAAAAA///gAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAH//4AAB/////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//////gAAAAAAAAAAAAAAAAA' +
  'AAAAAA//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//wAAA9////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////' +
  '//gAAAAAAAAAAAAAAAAAAAAAAAfwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP+AAAAA5////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAB////8eAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4AAAAAT////wAAAAAAGAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAA////wAAAAAADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAP///gAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////AAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH///AAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH////' +
  '/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH///AAAAAAAA8AAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAH/////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///AAAAAAAAcA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAD//+AAAAAAAAeYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAfvgAAAAAAAAf4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH////wAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAAAf4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH///w' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/gAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAH///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/A' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAYQAAAAAAAMOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//yAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf4AAAAAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//wA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP4AAAAAAAfgAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAP//6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP4AAAAAAA/AA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAb//+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAHwAAAAAAA+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAb//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAHgAAAAAAD8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//wA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/gAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAf//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/gAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//4AAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAf//gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB///gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB///AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//8AAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//8AA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAB//4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//AAAsAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//gAD' +
  '8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAA//wACQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf3wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/4AAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/+AA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAA//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD9gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH' +
  '4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQA' +
  'AAAAAAAAAAAAAAYAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/wAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAf/AAAAAAAAAAAAAAB/AA/wAAAAAHwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8A' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//gAAAAAAAAAcAAAH/wD//gH////8B+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//8AAAAAAAH///+f///////////////8AAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf////w/AAAAA/////////////' +
  '////////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////' +
  '///gAAP//////////////////////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP4AAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAcAD/////////gAAf///////////////////////4cAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAef/A' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/4P/////////wAB//////////////////////////gAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAA/f/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf////////////gD////////////////////////////gAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/f/wAAAAAAAAAAAAAAAAAAAAAAPwff/wAP////////////8AH///////////////' +
  '/////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/v/4AAAAAAAAAAAAAAAAAAAAAH//////////////////' +
  '///AP//////////////////////////////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/n/4AAAAAAAAAAAAAAAAHHh+' +
  'f//////////////////////A////////////////////////////////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAA//n/4' +
  'AAAAAAAAAAAAAAAAf/////////////////////////8B/////////////////////////////////AAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAA/+AAAAAAA9/n/8AAAAAAAAAAAAAAAA/////////////////////////////////////////////////////////////AAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAH8AAAQAAAAAAP/8AAAAAAAAAAAAAAAH////////////////////////////////////////////' +
  '////////////////+AAAAAAAAAAAAAAAAAAAACAQAAAAAH/wD5/4AYAA///+AAAAAAAAAAAAAAD/////////////////////////' +
  '////////////////////////////////////8AAAAAAAAAAAAAAAAAAAAA4fwAgAAD//////9/4f///+AAAAAAAAAAAAAAH/////' +
  '////////////////////////////////////////////////////////AAAAAAAAAAAAAAAAAABBAQAAP/wAAAf////////////4' +
  'AAAAAAAAAAAAAAB////////////////////////////////////////////////////////////8AAAAAAAAAAAAAAAAAA//////' +
  '///wAAH///////////+AAAAAAAAAAAAAAAP////////////////////////////////////////////////////////////gAAAA' +
  'AAAAAAAAAAACH/////////////////////////8AAAAAAAAAAAAAAB//////////////////////////////////////////////' +
  '///////////////AAAAAAAAAAAAAAAAf/////////////////////////8AAAAAAAAAAAAAAAf//////////////////////////' +
  '//////////////////////////////////8AAAAAAAAAAAAAAAAP////////////////////////+AAAAAAAAAAAAAAH////////' +
  '//////////////////////////////////////////////////////4AAAAAAAAAAAAAAAH///////////////////////+BAAAA' +
  'AAAAAAAAAAP///////////////////////////////////////////////////////////////4AAAAAAAAAAAAf/B//////////' +
  '///////////////AAAAAAAAAAAAAAB////////////////////////////////////////////////////////////////8AAAAA' +
  'AAAAAAAf///////////////////////////4AAAAAAAAIAAAB///////////////////////////////////////////////////' +
  '//////////////+AAAAAAAAAAEAP//////////////////////////wgAAAAAAAD/gAAf///////////////////////////////' +
  '///////////////////////////////////4AAAAAAAAAH8A//////////////////////////AAAAAAAAAP/4AA////////////' +
  '///////////////////////////////////////////////////////8AAAAAAAAAB/AAP////////////////////////AAAAAA' +
  'AAAf/4AA//////////////////////////////////////////////////////////////////AAAAAAAAAAAAAAAAB/////////' +
  '//////////////4AAAADAAB//8AAAAf//////////////////////////////////////////////////////////////8AAAAAA' +
  'AAAAAAAAAAAf///////////////////////AAA8PgA///wAAAAP/////////////////////////////////////////////////' +
  '/////////////8AAAAAAAAAAAAAAAAB/////////////////////////wAf/AAf/AAAAAf//////////////////////////////' +
  '/////////////////////////////////wAAAAAAAAAAAAAB/8///////////////////////////wAAAAAAAAAH////////////' +
  '/////////////////////////////////////////////////////8AAAAAAAAAAAAAAP//////////////////////////////A' +
  'AAAPwB////////////////////////////////////////////////////////////////////AAAAAAAAAAAAAAA///////////' +
  '///////////////////+AA////////////////////////////////////////////////////////////////////////4AAAAA' +
  'AAAAAAAAA///////////////////////////////wf//////////////////////////////////////////////////////////' +
  '///////////////gAAAAAAAAAAAAB///////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////AAAAAAAAAAAAB///////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////4AAAc8/+AAAAAB//////////////////////////////' +
  '/////////////////////////////////////////////////////////////////////////////8fg/////wAAAAAAf///////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '//////8D/+AP////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////';

let bits: Uint8Array | null = null;

/** Decoded on first use, then kept. Never decoded during a frame. */
function unpack(): Uint8Array {
  if (bits) return bits;
  const raw = atob(PACKED);
  const out = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) out[i] = raw.charCodeAt(i);
  bits = out;
  return out;
}

/** Land at this latitude/longitude in degrees. */
export function isLand(latDeg: number, lonDeg: number): boolean {
  const b = unpack();
  let row = Math.floor(((90 - latDeg) / 180) * H);
  let col = Math.floor(((lonDeg + 180) / 360) * W);
  if (row < 0) row = 0;
  else if (row >= H) row = H - 1;
  // Longitude wraps; latitude clamps. The date line is a seam only if the
  // column is clamped instead of wrapped, which shows as a bald stripe.
  col = ((col % W) + W) % W;
  const i = row * W + col;
  return (b[i >> 3] & (128 >> (i & 7))) !== 0;
}

/**
 * Land under a unit direction vector, y-up.
 *
 * The globe is built in direction space, so this is the form the generator
 * actually calls; it saves every caller repeating the same conversion and
 * getting the pole convention wrong half the time.
 */
export function isLandAtDirection(dx: number, dy: number, dz: number): boolean {
  const latDeg = Math.asin(Math.max(-1, Math.min(1, dy))) * (180 / Math.PI);
  const lonDeg = Math.atan2(dz, dx) * (180 / Math.PI);
  return isLand(latDeg, lonDeg);
}
